### ISSUE TITLE
Issue with Install

### ISSUE THREAD

**Issue by thomaskwok91** [juju-solutions/bundle-kubeflow#103]
Hi, when I was installing juju-solutions kubeflow I ran into an issue at this part

```python3 scripts/cli.py microk8s setup --controller uk8s```

The error message I got was:

`+ juju bootstrap microk8s uk8s
ERROR controller "uk8s" already exists
Command '('juju', 'bootstrap', 'microk8s', 'uk8s')' returned non-zero exit status 1.`

How do I fix this error?

Thanks

**Comment by camille-rodriguez** [comment]
Hi thomaswok91, 

Have you ran the command more than once? 
Try `juju list-controllers` to see if a controller named "uk8s" already exists.

If it shows up in the list and you want to start from scratch, you can delete it with `juju kill-controller uk8s` and launch the python3 script again. Otherwise, you can continue with the next step of the install.

**Comment by knkski** [comment]
Thanks @camille-rodriguez. @thomaskwok91, if `juju kill-controller uk8s` gives you any errors, you may need to run `juju unregister uk8s`, to tell Juju that the controller was destroyed behind the scenes and it should just forget about it.

Closing since you should have the steps to continue, but feel free to reopen if you encounter any issues.
