### ISSUE TITLE
Issue deploying stable kubeflow

### ISSUE THREAD

**Issue by aym-frikha** [juju-solutions/bundle-kubeflow#125]
I have this issue when deploying kubeflow on top of CDK:

python3 scripts/cli.py deploy-to cdkkf

Enter a password to set for the Kubeflow dashboard: 
Repeat for confirmation: 
+ juju add-model kubeflow cdkkf
Added 'kubeflow' model on cdkkf/us-east-1 with credential 'admin' for user 'admin'
+ juju kubectl apply -f resources/katib-configmap.yaml
configmap/katib-config created
+ juju kubectl apply -f resources/trial-template.yaml
configmap/trial-template created
+ juju deploy kubeflow --channel stable --overlay=/tmp/tmpczzzxln5
Located bundle "cs:bundle/kubeflow-115"
ERROR cannot deploy bundle: the provided bundle has the following errors:
empty charm path
invalid charm URL in application "pipelines-db": cannot parse URL "": name "" not valid
empty charm path
invalid charm URL in application "modeldb-db": cannot parse URL "": name "" not valid
Command '('juju', 'deploy', 'kubeflow', '--channel', 'stable', '--overlay=/tmp/tmpczzzxln5')' returned non-zero exit status 1.

It seems pipelines-db and modeldb-db does not exist anymore.

**Comment by aym-frikha** [comment]
root_password needs also to be changed to "root-password" as well as adding a new entry for mariadb

**Comment by knkski** [comment]
This should be fixed, in that I've pushed the edge channel to stable, which will work with the latest version of `cli.py` in this repo. The charms now require Juju 2.7+, which is currently in RC status, so you'll need to do `sudo snap switch juju --channel candidate`, then do `sudo snap refresh`. I'm closing this as fixed due to the above, but feel free to reopen if you encounter any issues.
